#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Cloud Agent install script for SkyNet-EnginX (ISP NetOps).
#
# Idempotent, one-time repository bootstrap. With environment builds this runs
# once to create the baseline snapshot, so it also seeds the local MariaDB with
# the schema and a default admin login. Per-boot service startup lives in
# start.sh, not here.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DB_NAME="isp_netops"
DB_USER="isp_netops"
DB_PASS="isp_netops_dev"

echo "==> [1/5] Installing MariaDB server (if needed)"
if ! command -v mariadbd >/dev/null 2>&1 && ! command -v mysqld >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq
  sudo apt-get install -y -qq mariadb-server
fi

echo "==> [2/5] Ensuring MariaDB data directory + server are up"
sudo mkdir -p /var/run/mysqld
sudo chown mysql:mysql /var/run/mysqld
# Initialize the system tables only if the data directory is empty.
if [ ! -d /var/lib/mysql/mysql ]; then
  sudo mariadb-install-db --user=mysql --datadir=/var/lib/mysql >/dev/null
fi
# Start the server (no systemd in the build/agent VM) and wait for readiness.
if ! sudo mysqladmin ping >/dev/null 2>&1; then
  sudo sh -c 'nohup mariadbd-safe >/var/log/mariadb-boot.log 2>&1 &'
fi
for i in $(seq 1 60); do
  if sudo mysqladmin ping >/dev/null 2>&1; then break; fi
  sleep 1
done
sudo mysqladmin ping

echo "==> [3/5] Creating database + dev user (idempotent)"
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
GRANT PROCESS ON *.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

echo "==> [4/5] Generating .env (if missing) + installing npm dependencies"
if [ ! -f .env ]; then
  cat > .env <<'ENV'
# Local development environment for SkyNet-EnginX (ISP NetOps)
# Generated by .cursor/install.sh. Safe local-only defaults (not real secrets).
APP_ENV=development
NODE_ENV=development
APP_PORT=3002
APP_URL=http://localhost:3002
BASE_URL=http://localhost:3002

# Database (MariaDB running locally in the VM)
DB_HOST=127.0.0.1
DB_PORT=3306
DB_NAME=isp_netops
DB_USER=isp_netops
DB_PASS=isp_netops_dev

# Auth secrets (local dev only — not real secrets)
JWT_SECRET=dev-jwt-secret-change-me
JWT_REFRESH_SECRET=dev-jwt-refresh-secret-change-me
JWT_PORTAL_SECRET=dev-jwt-portal-secret-change-me

# Misc
APP_TIMEZONE=Asia/Jakarta
LOG_LEVEL=info
ENV
  echo "    Wrote .env"
else
  echo "    .env already present — leaving as-is"
fi

npm ci

echo "==> [5/5] Seeding schema + default admin user"
node .cursor/seed-dev.js

echo "==> Install complete. Default login: admin@local.test / admin123"
